### ISSUE TITLE
analysis results

### ISSUE THREAD

**Issue by niloofartrg** [SpoonLabs/coming-experiments#1]
Bukkit
<img width="915" alt="Bukkit" src="https://user-images.githubusercontent.com/24320932/61816613-03254600-ae4d-11e9-827a-562f1f6aac1d.png">

commons_codec
![image](https://user-images.githubusercontent.com/24320932/61816679-2d770380-ae4d-11e9-88a5-d803cc330205.png)

commons_collections
<img width="904" alt="commons_collections" src="https://user-images.githubusercontent.com/24320932/61816764-51d2e000-ae4d-11e9-85d7-c2184dde6c2f.png">

commons_imaging
![image](https://user-images.githubusercontent.com/24320932/61816883-86df3280-ae4d-11e9-88b3-e19893fa5034.png)

commons_lang
![image](https://user-images.githubusercontent.com/24320932/61816927-a5ddc480-ae4d-11e9-8cb5-cab4f04edb47.png)

DiskLruCache.json
<img width="905" alt="DiskLruCache" src="https://user-images.githubusercontent.com/24320932/61816978-c148cf80-ae4d-11e9-9234-c095b3d3c7a0.png">

javapoet
<img width="909" alt="javapoet" src="https://user-images.githubusercontent.com/24320932/61817017-d58ccc80-ae4d-11e9-9f2d-e9c9e745f53a.png">

jsoup
<img width="905" alt="jsoup" src="https://user-images.githubusercontent.com/24320932/61817048-eb9a8d00-ae4d-11e9-8c38-06562e880777.png">

**Comment by niloofartrg** [comment]
Hi, These are the current results of the analysis on test datasets.

@martinezmatias @monperrus

**Comment by monperrus** [comment]
Cool, thanks for the first results. It seems that the number are really high. Why? Because we look for at least one change of the required type?

Should we add a filter on the maximum number of changes per commit?

**Comment by niloofartrg** [comment]
so you mean we should omit the commits that result in multiple repair tools? but why there is a big difference between the result of GenProg or NPEfix and the other repair tools?

**Comment by niloofartrg** [comment]
New results with applying the filter 
`-filter maxfiles -parameters max_files_per_commit:1
`
do these make more sense?

jsoup
<img width="848" alt="jsoup" src="https://user-images.githubusercontent.com/24320932/61895159-4695b800-af12-11e9-8e91-0fdf94381a9c.png">

Bukkit
<img width="587" alt="bukkit" src="https://user-images.githubusercontent.com/24320932/61895163-4990a880-af12-11e9-9415-1d54694b30e5.png">

commons-codec
<img width="739" alt="commons-codec" src="https://user-images.githubusercontent.com/24320932/61895169-4eedf300-af12-11e9-86fd-9ae350152dce.png">

commons-lang
<img width="569" alt="commons-lang" src="https://user-images.githubusercontent.com/24320932/61895175-56150100-af12-11e9-93d5-55c1fecc9bf2.png">

**Comment by monperrus** [comment]
cool. could you push the diff+label files in the repo?

**Comment by monperrus** [comment]
continuing with files in #2
